name: unit-test
description: "Runs the unit tests on GdUnit4 API"

inputs:
  godot-version:
    required: true
  godot-status:
    required: true
  paths:
    required: true

runs:
  using: composite
  steps:
    - name: Run Unit Tests
      uses: MikeSchulze/gdUnit4-action@v1.1.1
      with:
        godot-version: ${{ inputs.godot-version }}
        godot-status: ${{ inputs.godot-status }}
        paths: ${{ inputs.paths }}